apiVersion: v1
kind: Service
metadata:
  name: nagp-orders-service
  labels:
    app: orders-api
spec: 
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: orders-api