apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
  labels:
    app: apigateway
spec: 
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: apigateway